""" Contains configuration entries for biostudies client. """

import os

BIOSTUDIES_API_URL_DEV = 'http://biostudy-bia.ebi.ac.uk:8788'
BIOSTUDIES_API_URL = os.environ.get('BIOSTUDIES_API_URL', BIOSTUDIES_API_URL_DEV)

BIOSTUDIES_USERNAME_DEV = 'CHANGE_ME'
BIOSTUDIES_USERNAME = os.environ.get('BIOSTUDIES_USERNAME', BIOSTUDIES_USERNAME_DEV)

BIOSTUDIES_PASSWORD_DEV = 'CHANGE_ME'
BIOSTUDIES_PASSWORD = os.environ.get('BIOSTUDIES_PASSWORD', BIOSTUDIES_PASSWORD_DEV)
