LOGIN_TO_BST = 'auth/login'
CREATE_FOLDER = 'folder/user?folder={folder_name}'
UPLOAD_FILE = 'files/user'
GET_USER_FILES = 'files/user'
DELETE_USER_FILE = 'files/user'
CREATE_SUBMISSION = 'submissions'
